#%RAML 0.8
title: hybris Service Archetype
baseUri: http://localhost/
version: v1
mediaType:  application/json
schemas:
  - weather: !include weather.json
  - city: !include wcity.json
traits:
  - !include https://api.yaas.io/patterns/v2/trait-yaas-aware.yaml

resourceTypes:
  - !include https://api.yaas.io/patterns/v2/resource-type-element.yaml
  - !include https://api.yaas.io/patterns/v1/resource-type-collection.yaml

/weather:
  type: collection
  is: [yaasAware]
  get:
      description: get the weather for the given city
      responses:
        200:
          body:
            application/json
  /{city}:
    type: element
    is: [yaasAware]
    uriParameters:
      city:
        description: the name of the city
        example: Montreal
        type: string
    get:
      description: get the weather for the given city
      responses:
        200:
          body:
            application/json:
              example: wcity
